config/routes.rb
Rails.application.routes.draw do
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name,
            :address,
            :description,
            :price_per_night,
            :number_of_guests, presence: true

  validates :price_per_night,
            :number_of_guests, numericality: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :find_flat, only: %i[show edit update destroy]

  def index
    @flats = Flat.order('id DESC')
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)

    if @flat.save
      redirect_to flat_path(@flat)
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    @flat = Flat.find(params[:id])
    @flat.update(flat_params)

    redirect_to flat_path(@flat)
  end

  def destroy
    @flat.destroy

    redirect_to flats_path
  end

  private

  def find_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat)
          .permit(
            :name,
            :address,
            :description,
            :price_per_night,
            :number_of_guests
          )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for @flat do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :price_per_night %>
  <%= f.input :number_of_guests %>
  <%= f.button :submit, class: 'btn btn-primary' %>
<% end %>

app/views/flats/edit.html.erb
<h1 class="text-center">Edit <%= @flat.name %></h1>
<%= render 'form' %>

app/views/flats/index.html.erb
<div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 row-cols-lg-4">
  <% @flats.each do |flat| %>
    <div class="col mb-4">
      <div class="card h-100">
        <img src="https://source.unsplash.com/286x180/?apartment" class="card-img-top" alt="...">
        <div class="card-body">
          <h5 class="card-title"><%= flat.name %></h5>
          <p class="card-text"><%= flat.description %></p>
        </div>
        <div class="card-footer">
          <div class="d-flex justify-content-between">
            <div title="Number of guests">
              <i class="fas fa-users" style="color: #167FFB;"></i>
              <strong><%= flat.number_of_guests %></strong>
            </div>
            <div title="Price per night">
              <i class="fas fa-dollar-sign" style="color: green;"></i>
              <strong><%= flat.price_per_night %><small class="ml-1"><i>per night</i></small></strong>
            </div>
          </div>
          <hr>
          <div class="d-flex justify-content-between">
            <%= link_to flat_path(flat) do %>
              <i title="More Info" class="fas fa-info-circle" style="color: #167FFB;"></i>
            <% end %>

            <%= link_to edit_flat_path(flat) do %>
              <i title="Edit" class="fas fa-edit" style="color: #e67e22;"></i>
            <% end %>
            
            <%= link_to flat_path(flat),
                method: :delete, data: { confirm: 'Are you sure?' } do %>
                <i title="Delete "class="fas fa-trash" style="color: #fd1015;"></i>
            <% end %>            
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/flats/new.html.erb
<h1 class="text-center">New Flat</h1>
<%= render 'form' %>

app/views/flats/show.html.erb
<h1 class="text-center font-weight-bold mb-4"><%= @flat.name %></h1>

<h4>
  <p>
    <strong>Address: </strong><%= @flat.address %>
  </p>
  <p>
    <strong>
      Price: <i class="fas fa-dollar-sign" style="color: green;"></i>
      <%= @flat.price_per_night %><small class="ml-1"><i>per night</i></small>
    </strong>
  </p>
  <p>
    <strong>Max Guests: </strong><%= @flat.number_of_guests %>
  </p>
</h4>

<div class="container" style="max-width: 600px;">
  <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
      <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="https://source.unsplash.com/400x250/?apartment" class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item">
        <img src="https://source.unsplash.com/400x250/?bed" class="d-block w-100" alt="...">
      </div>
      <div class="carousel-item">
        <img src="https://source.unsplash.com/400x250/?kitchen" class="d-block w-100" alt="...">
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
  <br>
  <h4 class="text-center">
    <p><%= @flat.description %></p>
  </h4>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simple AirBnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <div class="container">
      <%= yield %>
    </div>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light mb-4">
  <a class="navbar-brand" href="/flats">AirBnB</a>
  <button class="navbar-toggler collapsed"
          type="button"
          data-toggle="collapse"
          data-target="#navbarNavAltMarkup"
          aria-controls="navbarNavAltMarkup"
          aria-expanded="false"
          aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="navbar-collapse collapse" id="navbarNavAltMarkup">
    <ul class="navbar-nav ml-auto">
      <a class="btn btn-outline-success" href="/flats/new">New Flat</a>
    </ul>
  </div>
</nav>